from crm import get_crm
from datetime import datetime, timezone, timedelta
BD_TZ = timezone(timedelta(hours=6))
crm = get_crm()
leads = crm.get_wl_all()
from collections import Counter
status_counts = Counter(l.get('Status','') for l in leads)
total = len(leads)
sent = sum(1 for l in leads if l.get('Status') in ('T1 Sent','T2 Sent','T3 Sent','T4 Sent'))
replied = sum(1 for l in leads if l.get('Reply Status',''))
interested = sum(1 for l in leads if l.get('Reply Status') == 'Interested')
qualified = status_counts.get('Qualified', 0)
now = datetime.now(BD_TZ).strftime('%Y-%m-%d %H:%M')
print(f'NanoSoft Daily Report - {now} BD')
print(f'Total leads: {total}')
print(f'Qualified (unsent): {qualified}')
print(f'T1 Sent: {status_counts.get("T1 Sent",0)}')
print(f'T2 Sent: {status_counts.get("T2 Sent",0)}')
print(f'T3 Sent: {status_counts.get("T3 Sent",0)}')
print(f'T4 Sent: {status_counts.get("T4 Sent",0)}')
print(f'Replied: {replied}')
print(f'Interested: {interested}')
print(f'Bounced: {status_counts.get("Bounced",0)}')
print(f'Unqualified: {status_counts.get("Unqualified",0)}')
